### PR TITLE
feat: Create CODEOWNERS

### PR DESCRIPTION
**Pull request by SgtPooki**

### CODE REVIEW

**Review by hacdias — APPROVED** [review]

**Comment by hacdias** [comment]
I approved this, but I think it'd be better if we could create a group instead of adding everyone manually here.

**Review by olizilla — CHANGES_REQUESTED** [review]
Can we use a group here or add me?

**Comment by SgtPooki** [comment]
> Can we use a group here or add me?

@olizilla 
We don't have a group in ipld that I'm aware of. We have teams in ipfs-shipyard and ipfs called "ipfs-gui". If you have permissions, could you create a group and add myself, lidel, and hacdias to it ?

**Comment by rvagg** [comment]
set something up in here and I'll :thumbsup: https://github.com/ipld/github-mgmt/blob/master/github/ipld.yml

**Comment by SgtPooki** [comment]
@olizilla @rvagg updates have been merged to the github-mgmt repo

**Pull request merged**
